NAME = Minishell
CC = cc
CFLAGS = -Wall -Werror -Wextra

# Directories
SRCDIR = src
OBJDIR = obj
LIBFTDIR = Libft

SRCS = src/minishell.c

OBJS = $(SRCS:%.c=%.o)

# Build the push_swap executable
all: $(NAME)

$(NAME): $(OBJS)
	cd $(LIBFTDIR) && make
	$(CC) $(CFLAGS) -o $(NAME) $(OBJS) -L$(LIBFTDIR) -lft

# Compile each .c file into .o files
%.o: %.c
	$(CC) -c $(CFLAGS) $< -o $@

# Clean object files
clean:
	cd $(LIBFTDIR) && make clean
	rm -f $(OBJS) $(BOBJS)

# Remove all files generated by make
fclean: clean
	cd $(LIBFTDIR) && make fclean
	rm -f $(NAME)

# Rebuild everything from scratch
re: fclean all

.PHONY: all bonus clean fclean re
